# Basic
title: wacsy j home
# subtitle: ä¸ªäººç«™
description: share and progress~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: wacsy hiden
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: let's share
url: "https://c.369159.xyz"

# åšå®¢æ˜¯å¦è‡ªåŠ¨ç”Ÿæˆç›®å½•ï¼Œfalseä¸ºä¸ç”Ÿæˆ
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com

# Social
social:
    # github: wacsy
    # zhihu:
    # jianshu:
    # twitter:
    mail: wacsy@me.com
    # rss:


# ç™¾åº¦ç»Ÿè®¡
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
baidu:
    id:

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id:
    host:


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}
    - {title: æŠ€æœ¯æ”¯æŒ, description: support, url: '/support'}
    - {title: å…³äºæˆ‘, description: about, url: '/about'}

plugins:
  - jekyll-paginate

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"
